/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Enum.java to edit this template
 */
package komunikacija;

import java.io.Serializable;

/**
 *
 * @author MataVS
 */
public enum Operacija implements Serializable{
   LOGIN,
   UCITAJ_TRKACE,
   OBRISI_TRKACA,
   UCITAJ_NIVO_FORME,
   DODAJ_TRKACA,
   UCITAJ_TRENINGE,
   OBRISI_TRENING,
   DODAJ_TRENING,
   OBRISI_NIVO_FORME,
   DODAJ_NIVO_FORME,
   UCITAJ_TRENERE,
   OBRISI_TRENERA,
   DODAJ_TRENERA,
   UCITAJ_SERTIFIKATE,
   OBRISI_SERTIFIKAT,
   DODAJ_SERTIFIKAT,
   AZURIRAJ_TRKACA,
   AZURIRAJ_TRENING,
   AZURIRAJ_NIVO_FORME,
   AZURIRAJ_TRENERA,
   AZURIRAJ_SERTIFIKAT,
   UCITAJ_EVIDENCIJE_TRENINGA,
   UCITAJ_STAVKE_EVIDENCIJE_TRENINGA,
   OBRISI_EVIDENCIJU_TRENINGA,
   DODAJ_EVIDENCIJU_TRENINGA,
   AZURIRAJ_EVIDENCIJU_TRENINGA,
   DODAJ_STAVKU_EVIDENCIJE_TRENINGA,
   OBRISI_STAVKU_EVIDENCIJE_TRENINGA,
   AZURIRAJ_STAVKU_EVIDENCIJE_TRENINGA,
   UCITAJ_TRENER_SERTIFIKAT,
   OBRISI_TRENER_SERTIFIKAT,
   DODAJ_TRENER_SERTIFIKAT,
   
}
